cilium_namespace: kube-system
cilium_repo_url: https://helm.cilium.io
cilium_values:
  hubble:
    relay:
      enabled: true
    ui:
      enabled: true
  k8sServiceHost: 127.0.0.1
  k8sServicePort: 6444
  kubeProxyReplacement: true
  l2announcements:
    enabled: true
  operator:
    replicas: 1
cilium_version: 1.15.1
